name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Microsoft OpenJDK 17
      run: |
        wget https://download.visualstudio.microsoft.com/download/pr/xxxxxx -O microsoft-jdk-17.tar.gz
        tar -xzf microsoft-jdk-17.tar.gz
        sudo mv jdk-17 /usr/lib/jvm/microsoft-jdk-17
        sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/microsoft-jdk-17/bin/java 1
        sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/microsoft-jdk-17/bin/javac 1
        sudo update-alternatives --install /usr/bin/javaws javaws /usr/lib/jvm/microsoft-jdk-17/bin/javaws 1
        java -version

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Upload JUnit test results
      uses: actions/upload-artifact@v3
      with:
        name: junit-results
        path: target/surefire-reports
