name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: jpa
          POSTGRES_USER: ahmad
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd="pg_isready -U ahmad -d jpa"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Set up PostgreSQL Database Connection
      run: |
        echo "spring.datasource.url=${{ secrets.DB_URL }}" >> src/main/resources/application.properties
        echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> src/main/resources/application.properties
        echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> src/main/resources/application.properties
        echo "spring.mail.host=${{ secrets.MAIL_HOST }}" >> src/main/resources/application.properties
        echo "spring.mail.port=${{ secrets.MAIL_PORT }}" >> src/main/resources/application.properties
        echo "spring.mail.username=${{ secrets.MAIL_USERNAME }}" >> src/main/resources/application.properties
        echo "spring.mail.password=${{ secrets.MAIL_PASSWORD }}" >> src/main/resources/application.properties

    - name: Build with Maven
      run: mvn clean install -B

    - name: Run tests
      run: mvn test -X

    - name: Upload JUnit test results
      uses: actions/upload-artifact@v3
      with:
        name: junit-results
        path: target/surefire-reports
