name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: adoptium
        java-package: jdk
        check-latest: false
        server-id: github
        server-username: ${{ secrets.GITHUB_ACTOR }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        job-status: success
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Upload JUnit test results
      uses: actions/upload-artifact@v3
      with:
        name: junit-results
        path: target/surefire-reports
